string = input("give a string: ").upper()
print("third character of this string: ", string[3])
print("second to last character of this string: ", string[-2])
print("first five characters of this string: ", string[:6])
print("all but the last two characters of this string: ", string[:-2])
print("all the characters of this string with even indices: ", string[1::2])
print("the characters of this string with odd indices: ", string[::2])
print("string in reverse: ", string[::-1])
print("len of string: ", len(string))
